[workspace]
resolver = "2"
members = [
    "wutengine",
    "wutengine/macro",
    "wutengine_editor",
    "wutengine_core",
    "wutengine_examples/pong",
    "wutengine_util/macro",
    "wutengine_graphics",
    "wutengine_opengl",
    "gl-from-raw-window-handle",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Wouter de Bruijn <wouter@wutru.io>"]
homepage = "https://github.com/cloone8/WutEngine"
repository = "https://github.com/cloone8/WutEngine"
license = "MPL-2.0"
keywords = []
categories = ["game-engines"]

[workspace.dependencies]
### Workspace dependencies ###
wutengine = { path = "wutengine", version = "0.1.0" }
wutengine_macro = { path = "wutengine/macro", version = "0.1.0" }
wutengine_core = { path = "wutengine_core", version = "0.1.0" }
wutengine_util_macro = { path = "wutengine_util/macro", version = "0.1.0" }
wutengine_graphics = { path = "wutengine_graphics", version = "0.1.0" }
wutengine_opengl = { path = "wutengine_opengl", version = "0.1.0" }
wutengine_ecs = { path = "wutengine_ecs", version = "0.1.0" }
gl-from-raw-window-handle = { path = "gl-from-raw-window-handle", version = "0.1.2" }

### External dependencies ###
# OS
cocoa = "0.26.0"
objc = "0.2.7"
core-foundation = "0.10.0"
x11 = { version = "2.21.0", features = ["xlib", "glx"] }
winapi = { version = "0.3.9", features = [
    "libloaderapi",
    "minwindef",
    "ntdef",
    "windef",
    "wingdi",
    "winnt",
    "winuser",
] }
uuid = { version = "1.13.1", features = ["v4"] }

# Windowing 
winit = { version = "0.30.9" }
gl_generator = "0.14.0"
raw-window-handle = "0.6.2"

# Gamepad
gilrs = { version = "0.11.0" }

# Logging and errors
log = "0.4.25"
simplelog = "0.12.2"
thiserror = "2.0.11"

# Math and algorithms
nohash-hasher = { version = "0.2.0" }
rand = { version = "0.9.0", features = ["std", "std_rng", "small_rng"] }
itertools = "0.14.0"
glam = { version = "0.29.2", features = ["std", "debug-glam-assert"] }

# Macro utilities
syn = { version = "2.0.98", features = ["full", "parsing"] }
quote = "1.0.38"
proc-macro2 = "1.0.93"
darling = "0.20.10"

# Parallellism
rayon = "1.10.0"

# Physics
rapier2d = { version = "0.23.0", features = ["simd-stable", "parallel"] }
rapier3d = { version = "0.23.0", features = ["simd-stable", "parallel"] }
nalgebra = { version = "0.*", features = ["convert-glam029"] }

# Others
static_assertions = "1.1.0"
include_dir = "0.7.4"

[profile.dev]
opt-level = 1
panic = "unwind"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "unwind"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
missing_docs_in_private_items = "warn"
