[workspace]
resolver = "2"
members = ["wutengine", "wutengine_examples/pong"]

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["Wouter de Bruijn <wouter@wutru.io>"]
homepage = "https://github.com/cloone8/WutEngine"
repository = "https://github.com/cloone8/WutEngine"
license = "MPL-2.0"
keywords = []
categories = ["game-engines"]

[workspace.dependencies]
wutengine = { path = "wutengine", version = "0.0.1" }
