[package]
name = "wutengine"
description = "A modern game engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

build = "build/main.rs"

[build-dependencies]
itertools.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true

[dependencies]
wutengine_core.workspace = true
wutengine_macro.workspace = true
wutengine_util_macro.workspace = true

nohash-hasher.workspace = true
winit.workspace = true
log.workspace = true
itertools.workspace = true
