[package]
name = "wutengine"
description = "A modern game engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
readme = "../README.md"

[lints]
workspace = true

[features]
default = ["opengl"]
opengl = ["dep:wutengine_opengl"]

[dependencies]
# Core
wutengine_core.workspace = true
wutengine_graphics.workspace = true
wutengine_macro.workspace = true
wutengine_util_macro.workspace = true
wutengine_ecs.workspace = true

# Renderers
wutengine_opengl = { workspace = true, optional = true }

# External
nohash-hasher.workspace = true
winit.workspace = true
log.workspace = true
itertools.workspace = true
rand.workspace = true
glam.workspace = true
include_dir.workspace = true
simplelog.workspace = true
