name: Publish

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XCB and GL dependencies (ubuntu runner)
        run: |
          sudo apt update
          sudo apt install libx11-xcb-dev libgl1-mesa-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish engine core
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine_core
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      
      - name: Publish engine utility macros
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine_util_macro
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish ECS
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine_ecs
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        
      - name: Publish engine graphics core
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine_graphics
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      
      - name: Publish OpenGL backend
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine_opengl
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      
      - name: Publish engine macros
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine_macro
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish main engine crate
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
