name: Publish

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish Engine Core
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine_core
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish Engine Serialization Datastructures
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine_serialized
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish Engine
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish Editor
        run: cargo publish --token ${CRATES_TOKEN} -p wutengine_editor
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
